### ISSUE TITLE
Consider using 8.x-2.x of Drupal Coder

### ISSUE THREAD

**Issue by Dropa** [willhallonline/docker-drupal-phpcs#1]
It's over a year now since last stable release of Drupal Coder and because of that, [this part of coder is missing](https://cgit.drupalcode.org/coder/commit/?id=6c357ae96ad7a69d60f58a03fabc07bc7beae842)

This means that when your readme (markdown) has link like above, you'll get fail for automated pipeline.

**Comment by willhallonline** [comment]
You are right. I have added in your adjustments and also changed a few things further up in the pipeline. It should not affect you, but **latest** of [willhallonline/phpcs](https://hub.docker.com/r/willhallonline/phpcs) is now **alpine** rather than **debian**.
